{# Jinja Template --> Sparql Query
 | Search for aphia taxnames and their labels (in a certain language)
 | variables in template:
 |    - (optional) N: number of triples to return (no limit applied when no N is given)
-#}
PREFIX taxn: <https://aphia.org/ns/taxon-name/>

select ?tn where { 
	?tn a taxn:TaxonName .
} 
{{ "LIMIT " ~ N   if N else "" }} {#- add limit  statement if provided #}